import {
  CanonicalPortfolioEntry,
  ClientItem,
  SemanticCategoryId,
} from "./types";

export const CATEGORY_DISPLAY_NAMES: Record<SemanticCategoryId, string> = {
  "product-design": "Product Design",
  "brand-identity": "Brand Identity",
  logos: "Logos",
  "corporate-identity": "Corporate Identity",
  "marketing-kit": "Marketing Kit",
  "graphic-visual": "Graphic & Visual",
  "social-media-content": "Social Media Content",
};

export const CANONICAL_PORTFOLIO_ENTRIES: CanonicalPortfolioEntry[] = [
  // ── 01. JANUS BIFROUS (Page 05) ──────────────────────────────────
  {
    id: "janus-bifrous",
    slug: "janus-bifrous",
    title: "JANUS BIFROUS",
    subtitle: "Artisan Beer",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    year: "2024",
    scope: ["Label Design", "Illustration", "Print Production", "Brand Identity"],
    description:
      "A dual-faced artisan beer packaging design exploring symmetry, mythology, and botanical textures. Built with tactile label materials and bespoke heraldic illustration.",
    number: "01",
    featured: true,
    published: true,
    order: 1,
    image: "/images/projects/janus-bifrous-hero.png",
    media: [
      {
        src: "/images/projects/janus-bifrous/bottle-left.png",
        alt: "JANUS BIFROUS - Bottle Front View on Warm Beige",
        width: 714,
        height: 795,
        aspectRatio: 714 / 795,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/janus-bifrous/circle-detail.png",
        alt: "JANUS BIFROUS - Brand Identity Emblem & Geometric Detail",
        width: 595,
        height: 795,
        aspectRatio: 595 / 795,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/janus-bifrous/bottle-right.png",
        alt: "JANUS BIFROUS - Bottle Angled View on Obsidian Black",
        width: 595,
        height: 795,
        aspectRatio: 595 / 795,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    images: [
      {
        src: "/images/projects/janus-bifrous/bottle-left.png",
        alt: "JANUS BIFROUS - Bottle Front View on Warm Beige",
        width: 714,
        height: 795,
        aspectRatio: 714 / 795,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/janus-bifrous/circle-detail.png",
        alt: "JANUS BIFROUS - Brand Identity Emblem & Geometric Detail",
        width: 595,
        height: 795,
        aspectRatio: 595 / 795,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/janus-bifrous/bottle-right.png",
        alt: "JANUS BIFROUS - Bottle Angled View on Obsidian Black",
        width: 595,
        height: 795,
        aspectRatio: 595 / 795,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    framingConfig: {
      mode: "auto",
      layoutMode: "auto",
      gap: "md",
      mobileStack: true,
    },
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 5,
      sourceCategory: "01 / DEP ROS PRODUCT DESIGN",
      sourceTitle: "JANUS BIFROUS",
      sourceSubtitle: "Artisan Beer",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 02. COCO FLAMINGO (Page 06) ──────────────────────────────────
  {
    id: "coco-flamingo",
    slug: "coco-flamingo",
    title: "COCO FLAMINGO",
    subtitle: "Summer Pale Ale",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    year: "2024",
    scope: ["Can Packaging", "Key Visual", "Art Direction", "Merchandise"],
    description:
      "Vibrant, sun-drenched visual identity and can packaging for a tropical pale ale series. Combining bold avian illustration with retro-modern typography.",
    number: "02",
    featured: true,
    published: true,
    order: 2,
    image: "/images/projects/coco-flamingo-hero.png",
    media: [
      {
        src: "/images/projects/coco-flamingo/flamingo-art.png",
        alt: "COCO FLAMINGO - Coconut Liqueur Illustrative Artwork",
        width: 516,
        height: 886,
        aspectRatio: 516 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/coco-flamingo/bottle-center.png",
        alt: "COCO FLAMINGO - Bottle Center Showcase",
        width: 733,
        height: 886,
        aspectRatio: 733 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/coco-flamingo/beach-bottles.png",
        alt: "COCO FLAMINGO - Tropical Lifestyle Duo",
        width: 654,
        height: 886,
        aspectRatio: 654 / 886,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    images: [
      {
        src: "/images/projects/coco-flamingo/flamingo-art.png",
        alt: "COCO FLAMINGO - Coconut Liqueur Illustrative Artwork",
        width: 516,
        height: 886,
        aspectRatio: 516 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/coco-flamingo/bottle-center.png",
        alt: "COCO FLAMINGO - Bottle Center Showcase",
        width: 733,
        height: 886,
        aspectRatio: 733 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/coco-flamingo/beach-bottles.png",
        alt: "COCO FLAMINGO - Tropical Lifestyle Duo",
        width: 654,
        height: 886,
        aspectRatio: 654 / 886,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    framingConfig: {
      mode: "auto",
      layoutMode: "auto",
      gap: "md",
      mobileStack: true,
    },
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 6,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "COCO FLAMINGO",
      sourceSubtitle: "Summer Pale Ale",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 03. KRAKEN RUM (Page 07) ──────────────────────────────────────
  {
    id: "kraken-rum",
    slug: "kraken-rum",
    title: "KRAKEN RUM",
    subtitle: "Spiced Rum Edition",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    year: "2023",
    scope: ["Bottle Packaging", "Embossed Label", "Custom Typography", "Box Design"],
    description:
      "Dark, ornate bottle packaging and label typography inspired by deep-sea nautical folklore and Victorian engraved bookplates.",
    number: "03",
    featured: true,
    published: true,
    order: 3,
    image: "/images/projects/kraken-rum-hero.png",
    media: [
      {
        src: "/images/projects/kraken-rum/bottle-left.png",
        alt: "KRAKEN RUM - Jamaican Rum Bottle Left View",
        width: 615,
        height: 886,
        aspectRatio: 615 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/kraken-rum/bottle-center.png",
        alt: "KRAKEN RUM - Bottle Center Showcase",
        width: 674,
        height: 886,
        aspectRatio: 674 / 886,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/kraken-rum/lifestyle-right.png",
        alt: "KRAKEN RUM - Maritime Lifestyle Right View",
        width: 615,
        height: 886,
        aspectRatio: 615 / 886,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    images: [
      {
        src: "/images/projects/kraken-rum/bottle-left.png",
        alt: "KRAKEN RUM - Jamaican Rum Bottle Left View",
        width: 615,
        height: 886,
        aspectRatio: 615 / 886,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/kraken-rum/bottle-center.png",
        alt: "KRAKEN RUM - Bottle Center Showcase",
        width: 674,
        height: 886,
        aspectRatio: 674 / 886,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/kraken-rum/lifestyle-right.png",
        alt: "KRAKEN RUM - Maritime Lifestyle Right View",
        width: 615,
        height: 886,
        aspectRatio: 615 / 886,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    framingConfig: {
      mode: "auto",
      layoutMode: "auto",
      gap: "md",
      mobileStack: true,
    },
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 7,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "KRAKEN RUM",
      sourceSubtitle: "Spiced Rum Edition",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 04. BLONDE ALE / GOLDEN ALE (Page 08) ────────────────────────
  {
    id: "blonde-ale",
    slug: "blonde-ale",
    title: "BLONDE ALE / GOLDEN ALE",
    subtitle: "Craft Beer Series",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    number: "04",
    featured: false,
    published: true,
    order: 4,
    image: "/images/projects/blonde-ale-hero.png",
    media: [
      {
        src: "/images/projects/blonde-ale-hero.png",
        alt: "BLONDE ALE / GOLDEN ALE - Craft Beer Series Packaging Lineup",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/blonde-ale-hero.png",
        alt: "BLONDE ALE / GOLDEN ALE - Craft Beer Series Packaging Lineup",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 8,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "BLONDE ALE / GOLDEN ALE",
      sourceSubtitle: "Craft Beer Series",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 05. LOCALE FRUIT WINE (Page 09) ──────────────────────────────
  {
    id: "locale-fruit-wine",
    slug: "locale-fruit-wine",
    title: "LOCALE FRUIT WINE",
    subtitle: "Cultured Beverages",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    number: "05",
    featured: false,
    published: true,
    order: 5,
    image: "/images/projects/locale-fruit-wine-hero.png",
    media: [
      {
        src: "/images/projects/locale-fruit-wine-hero.png",
        alt: "LOCALE FRUIT WINE - Cultured Beverages Bottle Lineup",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/locale-fruit-wine-hero.png",
        alt: "LOCALE FRUIT WINE - Cultured Beverages Bottle Lineup",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 9,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "LOCALE FRUIT WINE",
      sourceSubtitle: "Cultured Beverages",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 06. MINI LIQUEUR PARTY (Page 10) ─────────────────────────────
  {
    id: "mini-liqueur-party",
    slug: "mini-liqueur-party",
    title: "MINI LIQUEUR PARTY",
    subtitle: "Event Edition Series",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Locale Brewery",
    number: "06",
    featured: false,
    published: true,
    order: 6,
    image: "/images/projects/mini-liqueur-party-hero.png",
    media: [
      {
        src: "/images/projects/mini-liqueur-party-hero.png",
        alt: "MINI LIQUEUR PARTY - Event Edition Series Packaging Collection",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/mini-liqueur-party-hero.png",
        alt: "MINI LIQUEUR PARTY - Event Edition Series Packaging Collection",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 10,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "MINI LIQUEUR PARTY",
      sourceSubtitle: "Event Edition Series",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 07. BERASSA SNACK (Page 11) ──────────────────────────────────
  {
    id: "berassa-snack",
    slug: "berassa-snack",
    title: "BERASSA SNACK",
    subtitle: "Modern Heritage Snack",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Gumindo Bogamanis",
    number: "07",
    featured: false,
    published: true,
    order: 7,
    image: "/images/projects/berassa-snack-hero.png",
    media: [
      {
        src: "/images/projects/berassa-snack-hero.png",
        alt: "BERASSA SNACK - Modern Heritage Snack Packaging Pouch",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/berassa-snack-hero.png",
        alt: "BERASSA SNACK - Modern Heritage Snack Packaging Pouch",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 11,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "BERASSA SNACK",
      sourceSubtitle: "Modern Heritage Snack",
      sourceClient: "Gumindo Bogamanis",
    },
  },

  // ── 08. ARIN ARAK LIQUEUR (Page 12) ──────────────────────────────
  {
    id: "arin-arak",
    slug: "arin-arak",
    title: "ARIN ARAK LIQUEUR",
    subtitle: "Traditional Spirit Redesign",
    category: "product-design",
    categorySlug: "product-design",
    presentationType: "standalone",
    client: "Arin",
    number: "08",
    featured: false,
    published: true,
    order: 8,
    image: "/images/projects/arin-arak-hero.png",
    media: [
      {
        src: "/images/projects/arin-arak-hero.png",
        alt: "ARIN ARAK LIQUEUR - Traditional Spirit Redesign Bottle Packaging",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/arin-arak-hero.png",
        alt: "ARIN ARAK LIQUEUR - Traditional Spirit Redesign Bottle Packaging",
        width: 1584,
        height: 754,
        aspectRatio: 1584 / 754,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 12,
      sourceCategory: "PRODUCT DESIGN",
      sourceTitle: "ARIN ARAK LIQUEUR",
      sourceSubtitle: "Traditional Spirit Redesign",
      sourceClient: "Arin",
    },
  },

  // ── 09. MITRA KOPLING (Page 13) ──────────────────────────────────
  {
    id: "mitra-kopling",
    slug: "mitra-kopling",
    title: "MITRA KOPLING",
    subtitle: "Identity System & Brand Implementation",
    category: "brand-identity",
    categorySlug: "brand-identity",
    presentationType: "standalone",
    client: "Kapal Api",
    year: "2023",
    scope: ["Brand Strategy", "Visual Identity", "Signage System", "Guidelines"],
    description:
      "Modern, iconic, unique, reachable, humble. A complete visual identity and merchandise system crafted for the mobile coffee vendor community.",
    number: "09",
    featured: true,
    published: true,
    order: 9,
    image: "/images/projects/mitra-kopling-hero.png",
    media: [
      {
        src: "/images/projects/mitra-kopling/brand-guide.png",
        alt: "MITRA KOPLING - Brand Guidelines & Grid System",
        width: 575,
        height: 931,
        aspectRatio: 575 / 931,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/mitra-kopling/merchandise.png",
        alt: "MITRA KOPLING - Merchandise & Vehicle Branding",
        width: 833,
        height: 931,
        aspectRatio: 833 / 931,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/mitra-kopling/apparel.png",
        alt: "MITRA KOPLING - Community Uniform & Apparel",
        width: 496,
        height: 931,
        aspectRatio: 496 / 931,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    images: [
      {
        src: "/images/projects/mitra-kopling/brand-guide.png",
        alt: "MITRA KOPLING - Brand Guidelines & Grid System",
        width: 575,
        height: 931,
        aspectRatio: 575 / 931,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/mitra-kopling/merchandise.png",
        alt: "MITRA KOPLING - Merchandise & Vehicle Branding",
        width: 833,
        height: 931,
        aspectRatio: 833 / 931,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/mitra-kopling/apparel.png",
        alt: "MITRA KOPLING - Community Uniform & Apparel",
        width: 496,
        height: 931,
        aspectRatio: 496 / 931,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    framingConfig: {
      mode: "auto",
      layoutMode: "auto",
      gap: "md",
      mobileStack: true,
    },
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 13,
      sourceCategory: "02 / DEP ROS BRAND IDENTITY",
      sourceTitle: "MITRA KOPLING",
      sourceSubtitle: "Identity System & Brand Implementation",
      sourceClient: "Kapal Api",
    },
  },

  // ── 10. WHYSUPER & MILLIMETER (Page 15) ──────────────────────────
  {
    id: "whysuper-millimeter",
    slug: "whysuper-millimeter",
    title: "WHYSUPER & MILLIMETER",
    subtitle: "Brand System, Stationery & Guidelines",
    category: "corporate-identity",
    categorySlug: "corporate-identity",
    presentationType: "standalone",
    client: "Whysuper / Millimeter",
    year: "2024",
    scope: ["Corporate Identity", "Stationery Suite", "Print Finishes", "Folder Design"],
    description:
      "Modern, simplicity, solid, detail, presized, geometric, sustainability. Precision stationery layout and comprehensive visual system guidelines.",
    number: "10",
    featured: true,
    published: true,
    order: 10,
    image: "/images/projects/whysuper-corporate-hero.png",
    media: [
      {
        src: "/images/projects/whysuper-millimeter/stationery-left.png",
        alt: "WHYSUPER & MILLIMETER - Corporate Stationery System",
        width: 714,
        height: 931,
        aspectRatio: 714 / 931,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/whysuper-millimeter/cards-center.png",
        alt: "WHYSUPER & MILLIMETER - Business Cards & Grid Identity",
        width: 773,
        height: 931,
        aspectRatio: 773 / 931,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/whysuper-millimeter/guidelines-right.png",
        alt: "WHYSUPER & MILLIMETER - Brand Guidelines Manual",
        width: 417,
        height: 931,
        aspectRatio: 417 / 931,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    images: [
      {
        src: "/images/projects/whysuper-millimeter/stationery-left.png",
        alt: "WHYSUPER & MILLIMETER - Corporate Stationery System",
        width: 714,
        height: 931,
        aspectRatio: 714 / 931,
        orientation: "portrait",
        role: "primary",
      },
      {
        src: "/images/projects/whysuper-millimeter/cards-center.png",
        alt: "WHYSUPER & MILLIMETER - Business Cards & Grid Identity",
        width: 773,
        height: 931,
        aspectRatio: 773 / 931,
        orientation: "portrait",
        role: "detail",
      },
      {
        src: "/images/projects/whysuper-millimeter/guidelines-right.png",
        alt: "WHYSUPER & MILLIMETER - Brand Guidelines Manual",
        width: 417,
        height: 931,
        aspectRatio: 417 / 931,
        orientation: "portrait",
        role: "supporting",
      },
    ],
    framingConfig: {
      mode: "auto",
      layoutMode: "auto",
      gap: "md",
      mobileStack: true,
    },
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 15,
      sourceCategory: "04 / DEP ROS CORPORATE IDENTITY",
      sourceTitle: "WHYSUPER & MILLIMETER",
      sourceSubtitle: "Brand System, Stationery & Guidelines",
      sourceClient: "Whysuper / Millimeter",
    },
  },

  // ── 11. E-BOOK MARKETING KIT (Page 16) ───────────────────────────
  {
    id: "e-book-marketing",
    slug: "e-book-marketing",
    title: "E-BOOK MARKETING KIT",
    subtitle: "Comprehensive Guide",
    category: "marketing-kit",
    categorySlug: "marketing-kit",
    contentSubtype: "marketing-kit",
    presentationType: "standalone",
    client: "Eco Mailing",
    number: "11",
    featured: false,
    published: true,
    order: 11,
    image: "/images/projects/e-book-marketing-hero.png",
    media: [
      {
        src: "/images/projects/e-book-marketing-hero.png",
        alt: "E-BOOK MARKETING KIT - Comprehensive Digital Marketing Guide for Eco Mailing",
        width: 1584,
        height: 763,
        aspectRatio: 1584 / 763,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/e-book-marketing-hero.png",
        alt: "E-BOOK MARKETING KIT - Comprehensive Digital Marketing Guide for Eco Mailing",
        width: 1584,
        height: 763,
        aspectRatio: 1584 / 763,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 16,
      sourceCategory: "MARKETING KIT",
      sourceTitle: "E-BOOK MARKETING KIT",
      sourceSubtitle: "Comprehensive Guide",
      sourceClient: "Eco Mailing",
    },
  },

  // ── 12. SERVICE KIT SALES TOOLS (Page 17) ────────────────────────
  {
    id: "sales-tools",
    slug: "sales-tools",
    title: "SERVICE KIT SALES TOOLS",
    subtitle: "B2B Sales Presentation",
    category: "marketing-kit",
    categorySlug: "marketing-kit",
    contentSubtype: "sales-tools",
    presentationType: "standalone",
    client: "Suit Solution Group",
    number: "12",
    featured: false,
    published: true,
    order: 12,
    image: "/images/projects/sales-tools-hero.png",
    media: [
      {
        src: "/images/projects/sales-tools-hero.png",
        alt: "SERVICE KIT SALES TOOLS - B2B Sales Presentation Deck for Suit Solution Group",
        width: 1584,
        height: 763,
        aspectRatio: 1584 / 763,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/sales-tools-hero.png",
        alt: "SERVICE KIT SALES TOOLS - B2B Sales Presentation Deck for Suit Solution Group",
        width: 1584,
        height: 763,
        aspectRatio: 1584 / 763,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 17,
      sourceCategory: "SALES TOOLS",
      sourceTitle: "SERVICE KIT SALES TOOLS",
      sourceSubtitle: "B2B Sales Presentation",
      sourceClient: "Suit Solution Group",
    },
  },

  // ── 13. LOCALE INSTAGRAM FEEDS (Page 19) ─────────────────────────
  {
    id: "locale-social",
    slug: "locale-social",
    title: "LOCALE INSTAGRAM FEEDS",
    subtitle: "Visual Grid Strategy & Content Creation",
    category: "social-media-content",
    categorySlug: "social-media-content",
    presentationType: "standalone",
    client: "Locale Brewery",
    number: "13",
    featured: false,
    published: true,
    order: 13,
    image: "/images/projects/locale-social-hero.png",
    media: [
      {
        src: "/images/projects/locale-social-hero.png",
        alt: "LOCALE INSTAGRAM FEEDS - Social Grid Strategy and Visual Content for Locale Brewery",
        width: 1584,
        height: 709,
        aspectRatio: 1584 / 709,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/locale-social-hero.png",
        alt: "LOCALE INSTAGRAM FEEDS - Social Grid Strategy and Visual Content for Locale Brewery",
        width: 1584,
        height: 709,
        aspectRatio: 1584 / 709,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 19,
      sourceCategory: "05/ DEP ROS SOCIAL MEDIA CONTENT",
      sourceTitle: "LOCALE INSTAGRAM FEEDS",
      sourceSubtitle: "Visual Grid Strategy & Content Creation",
      sourceClient: "Locale Brewery",
    },
  },

  // ── 14. KOPI TUNGKU INSTAGRAM STORY (Page 20) ───────────────────
  {
    id: "kopi-tungku",
    slug: "kopi-tungku",
    title: "KOPI TUNGKU INSTAGRAM STORY",
    subtitle: "Daily Content & Promotional Stories",
    category: "social-media-content",
    categorySlug: "social-media-content",
    presentationType: "standalone",
    client: "Kopi Tungku",
    number: "14",
    featured: false,
    published: true,
    order: 14,
    image: "/images/projects/kopi-tungku-hero.png",
    media: [
      {
        src: "/images/projects/kopi-tungku-hero.png",
        alt: "KOPI TUNGKU INSTAGRAM STORY - Daily Content and Promotional Stories",
        width: 1584,
        height: 800,
        aspectRatio: 1584 / 800,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/kopi-tungku-hero.png",
        alt: "KOPI TUNGKU INSTAGRAM STORY - Daily Content and Promotional Stories",
        width: 1584,
        height: 800,
        aspectRatio: 1584 / 800,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 20,
      sourceCategory: "SOCIAL MEDIA CONTENT",
      sourceTitle: "KOPI TUNGKU INSTAGRAM STORY",
      sourceSubtitle: "Daily Content & Promotional Stories",
      sourceClient: "Kopi Tungku",
    },
  },

  // ── 15. LOGOS COLLECTION (Page 14 — Grouped Presentation) ────────
  {
    id: "logos-collection",
    slug: "logos-collection",
    title: "LOGOS COLLECTION",
    subtitle: "Selected Marks & Symbols (2020–2026)",
    category: "logos",
    categorySlug: "logos",
    presentationType: "grouped",
    number: "15",
    featured: false,
    published: true,
    order: 15,
    image: "/images/projects/logos-collection-hero.png",
    media: [
      {
        src: "/images/projects/logos-collection-hero.png",
        alt: "DEPROS LOGOS COLLECTION - Selected Marks and Brand Symbols Grid",
        width: 1584,
        height: 800,
        aspectRatio: 1584 / 800,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/logos-collection-hero.png",
        alt: "DEPROS LOGOS COLLECTION - Selected Marks and Brand Symbols Grid",
        width: 1584,
        height: 800,
        aspectRatio: 1584 / 800,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 14,
      sourceCategory: "03 / DEP ROS LOGOS",
      sourceTitle: "LOGOS",
      sourceSubtitle: "Selected Marks & Symbols (2020–2026)",
    },
  },

  // ── 16. GRAPHIC & VISUAL (Page 18 — Grouped Presentation) ────────
  {
    id: "graphic-visual",
    slug: "graphic-visual",
    title: "GRAPHIC & VISUAL",
    subtitle: "Floor / Wall Images / Visual Card / Graphic & Else",
    category: "graphic-visual",
    categorySlug: "graphic-visual",
    presentationType: "grouped",
    number: "16",
    featured: false,
    published: true,
    order: 16,
    image: "/images/projects/bounce-bali-hero.png",
    media: [
      {
        src: "/images/projects/bounce-bali-hero.png",
        alt: "DEPROS Environmental Graphics, Wall Murals, and Visual Artwork",
        width: 1584,
        height: 782,
        aspectRatio: 1584 / 782,
        orientation: "landscape",
        role: "composite",
      },
    ],
    images: [
      {
        src: "/images/projects/bounce-bali-hero.png",
        alt: "DEPROS Environmental Graphics, Wall Murals, and Visual Artwork",
        width: 1584,
        height: 782,
        aspectRatio: 1584 / 782,
        orientation: "landscape",
        role: "composite",
      },
    ],
    provenance: {
      sourceDocument: "PF DEPROS 2026_B.pdf",
      sourcePage: 18,
      sourceCategory: "GRAPHIC & VISUAL",
      sourceTitle: "FLOOR / WALL IMAGES / VISUAL CARD / GRAPHIC & ELSE",
      sourceSubtitle: "Environmental & Spatial Graphic Design",
    },
  },
];

export const FEATURED_PROJECTS = CANONICAL_PORTFOLIO_ENTRIES;

export const NOTABLE_CLIENTS: ClientItem[] = [
  {
    id: "nusa-dua-beach-hotel",
    name: "Nusa Dua Beach Hotel",
    scope: "Logo & collateral redesign",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "westin-nusa-dua",
    name: "Westin Nusa Dua",
    scope: "Marketing Ads",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "niko-bali",
    name: "Niko Bali",
    scope: "Logo redesign",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "sunset-island-property",
    name: "Sunset Island Property",
    scope: "Brand Identity",
    industry: "Hospitality, Property",
    location: "Kuta, Bali",
  },
  {
    id: "waterbom-bali",
    name: "Water Bom Bali",
    scope: "Wayfinding & Marketing Ads",
    industry: "Water Park",
    location: "Kuta, Bali",
  },
  {
    id: "3v-villas-kerobokan",
    name: "3V Villas Kerobokan",
    scope: "Brand Id, Visual Assets & Art Directions",
    industry: "Hospitality",
    location: "Kerobokan, Bali",
  },
  {
    id: "3v-resort-rening",
    name: "3V Resort Rening",
    scope: "Brand Development",
    industry: "Hospitality",
    location: "Rening Bay, West Bali",
  },
  {
    id: "sundays-beach-club",
    name: "Sundays Beach Club",
    scope: "Marketing Ads",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "aloita-resort-batam",
    name: "Aloita Resort Batam",
    scope: "Brand Strategy & Identity",
    industry: "Hospitality & Tourism",
    location: "Batam Island",
  },
  {
    id: "finns-beach-club",
    name: "Finns Beach Club",
    scope: "Brand Identity, Visual Assets & Art Directions",
    industry: "Hospitality",
    location: "Canggu Bali",
  },
  {
    id: "finns-recreation-club",
    name: "Finns Recreation Club",
    scope: "Brand Identity, Visual Assets & Art Directions",
    industry: "Hospitality, Amusement",
    location: "Canggu Bali",
  },
  {
    id: "bisma-cottages-ubud",
    name: "Bisma Cottages Ubud",
    scope: "Digital Contents, Marketing Ads",
    industry: "Hospitality",
    location: "Ubud, Bali",
  },
];

export const STUDIO_CAPABILITIES = [
  "brand development",
  "creative direction",
  "graphic design",
  "product design",
  "digital marketing",
  "social media concept",
  "social media content",
  "print-ready artwork",
];
