import { Project, ClientItem } from "./types";

export const FEATURED_PROJECTS: Project[] = [
  {
    id: "janus-bifrous",
    number: "01",
    title: "JANUS BIFROUS",
    subtitle: "Herbs Liqueur",
    category: "01 / PRODUCT DESIGN",
    categorySlug: "product-design",
    client: "LOCALE BREWERY",
    description:
      "Product packaging and label artwork for Janus Bifrous Herbs Liqueur. Crafted with distinct typography and disciplined layout.",
    image: "/images/projects/janus-bifrous/hero.png",
    year: "2024",
    scope: ["Product Design", "Packaging", "Label Artwork"],
    featured: true,
  },
  {
    id: "coco-flamingo",
    number: "02",
    title: "COCO FLAMINGO",
    subtitle: "Coconut Liqueur",
    category: "01 / PRODUCT DESIGN",
    categorySlug: "product-design",
    client: "LOCALE BREWERY",
    description:
      "Packaging and illustrative design for Coco Flamingo Coconut Liqueur, pairing expressive character with clean structural geometry.",
    image: "/images/projects/coco-flamingo/hero.png",
    year: "2024",
    scope: ["Product Design", "Packaging", "Illustration"],
    featured: true,
  },
  {
    id: "kraken-rum",
    number: "03",
    title: "KRAKEN RUM",
    subtitle: "Jamaican Style Rum",
    category: "01 / PRODUCT DESIGN",
    categorySlug: "product-design",
    client: "LOCALE BREWERY",
    description:
      "Product design and thematic label illustration for Kraken Rum, balancing maritime narrative with bold shelf presence.",
    image: "/images/projects/kraken-rum/hero.png",
    year: "2024",
    scope: ["Product Design", "Packaging", "Illustration"],
    featured: true,
  },
  {
    id: "mitra-kopling",
    number: "04",
    title: "MITRA KOPLING",
    subtitle: "Komunitas Pedagang Kopi Keliling",
    category: "02 / BRAND IDENTITY",
    categorySlug: "brand-identity",
    client: "KAPAL API",
    description:
      "Modern, iconic, unique, reachable, humble. A complete visual identity and merchandise system crafted for the mobile coffee vendor community.",
    image: "/images/projects/mitra-kopling/hero.png",
    year: "2023",
    scope: ["Brand Identity", "Visual Assets", "Merchandise Design"],
    featured: true,
  },
  {
    id: "whysuper-millimeter",
    number: "05",
    title: "WHYSUPER & MILLIMETER",
    subtitle: "Corporate Stationery & Guidelines",
    category: "04 / CORPORATE IDENTITY",
    categorySlug: "corporate-identity",
    client: "WHYSUPER & MILLIMETER",
    description:
      "Modern, simplicity, solid, detail, presized, geometric, sustainability. Precision stationery layout and comprehensive visual system guidelines.",
    image: "/images/projects/whysuper-millimeter/hero.png",
    year: "2023",
    scope: ["Corporate Identity", "Stationery System", "Brand Guidelines"],
    featured: true,
  },
];

export const NOTABLE_CLIENTS: ClientItem[] = [
  {
    id: "nusa-dua-beach-hotel",
    name: "Nusa Dua Beach Hotel",
    scope: "Logo & collateral redesign",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "westin-nusa-dua",
    name: "Westin Nusa Dua",
    scope: "Marketing Ads",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "niko-bali",
    name: "Niko Bali",
    scope: "Logo redesign",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "sunset-island-property",
    name: "Sunset Island Property",
    scope: "Brand Identity",
    industry: "Hospitality, Property",
    location: "Kuta, Bali",
  },
  {
    id: "waterbom-bali",
    name: "Water Bom Bali",
    scope: "Wayfinding & Marketing Ads",
    industry: "Water Park",
    location: "Kuta, Bali",
  },
  {
    id: "3v-villas-kerobokan",
    name: "3V Villas Kerobokan",
    scope: "Brand Id, Visual Assets & Art Directions",
    industry: "Hospitality",
    location: "Kerobokan, Bali",
  },
  {
    id: "3v-resort-rening",
    name: "3V Resort Rening",
    scope: "Brand Development",
    industry: "Hospitality",
    location: "Rening Bay, West Bali",
  },
  {
    id: "sundays-beach-club",
    name: "Sundays Beach Club",
    scope: "Marketing Ads",
    industry: "Hospitality",
    location: "Nusa Dua, Bali",
  },
  {
    id: "aloita-resort-batam",
    name: "Aloita Resort Batam",
    scope: "Brand Strategy & Identity",
    industry: "Hospitality & Tourism",
    location: "Batam Island",
  },
  {
    id: "finns-beach-club",
    name: "Finns Beach Club",
    scope: "Brand Identity, Visual Assets & Art Directions",
    industry: "Hospitality",
    location: "Canggu Bali",
  },
  {
    id: "finns-recreation-club",
    name: "Finns Recreation Club",
    scope: "Brand Identity, Visual Assets & Art Directions",
    industry: "Hospitality, Amusement",
    location: "Canggu Bali",
  },
  {
    id: "bisma-cottages-ubud",
    name: "Bisma Cottages Ubud",
    scope: "Digital Contents, Marketing Ads",
    industry: "Hospitality",
    location: "Ubud, Bali",
  },
];

export const STUDIO_CAPABILITIES = [
  "brand development",
  "creative direction",
  "graphic design",
  "product design",
  "digital marketing",
  "social media concept",
  "social media content",
  "print-ready artwork",
];
